services:
  magic:
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./application/mage_ai/Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
      MINIO_ROOT_USER: ${MINIO_ADMIN}
      MINIO_ROOT_PASSWORD: ${MINIO_PWD}
      MINIO_ENDPOINT: ${MINIO_URL}
      MAGE_BASE_PATH: mage
      MAGE_DATA_DIR: /home/src/mage_data
      REQUIRE_USER_AUTHENTICATION: 0
      GOOGLE_APPLICATION_CREDENTIALS: /home/src/google_service_account.json
    ports:
      - 6789:6789
    volumes:
      - ./application/mage_ai/:/home/src
      - ./application/mage_ai/aws:/root/.aws
      - ./application/mage_ai/google_service_account.json:/home/src/google_service_account.json:ro
    networks:
      - ndsnet
    restart: on-failure:5

  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
      - ./storage/export:/export
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN}
      MINIO_ROOT_PASSWORD: ${MINIO_PWD}
      MINIO_BROWSER_REDIRECT_URL: http://localhost/minio/
    command: server --console-address ":9001" /data
    networks:
      - ndsnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  jupyterlab:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./application/jupyterlab/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./application/jupyterlab/data:/opt/app/data
    environment:
      JUPYTER_ENABLE_LAB: 1
      NB_USER: jovyan
      NB_GID: 1000
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'
    networks:
      - ndsnet

  warehouse_db:
    build:
      context: .
      dockerfile: ./application/warehouse_db/Dockerfile
    hostname: warehouse_db
    environment:
      POSTGRES_USER: ${WAREHOUSE_DB_USER}
      POSTGRES_PASSWORD: ${WAREHOUSE_DB_PASS}
      POSTGRES_DB: ${WAREHOUSE_DB_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./database/warehouse_db:/var/lib/postgresql/data
      - ./application/warehouse_db/init:/docker-entrypoint-initdb.d
    networks:
      - ndsnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${WAREHOUSE_DB_USER} -d ${WAREHOUSE_DB_DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.3-e.8'
    ports:
      - '9083:9083'
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://warehouse_db:5432/metastore
      HIVE_METASTORE_USER: ${WAREHOUSE_DB_USER}
      HIVE_METASTORE_PASSWORD: ${WAREHOUSE_DB_PASS}
      HIVE_METASTORE_WAREHOUSE_DIR: s3a://dwhfilesystem/
      S3_ENDPOINT: ${MINIO_URL}
      S3_ACCESS_KEY: ${MINIO_ADMIN}
      S3_SECRET_KEY: ${MINIO_PWD}
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      warehouse_db:
        condition: service_healthy
    networks:
      - ndsnet
  metabase:
    env_file:
      - .env
    volumes:
      - ./application/metabase:/metabase-data
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=warehouse_db
      - MB_DB_PORT=5432
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_USER=${WAREHOUSE_DB_USER}
      - MB_DB_PASS=${WAREHOUSE_DB_PASS}
      - MB_SITE_URL=http://localhost/metabase/
    ports:
      - 3000:3000
    image: metabase/metabase
    restart: always
    depends_on:
      - warehouse_db
    networks:
      - ndsnet

  anything-llm:
    container_name: anythingllm
    image: mintplexlabs/anythingllm:pg
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./application/anythingllm.env:/app/server/.env"
      - "./data/anythingllm/server/storage:/app/server/storage"
      - "./data/anythingllm/collector/hotdir/:/app/collector/hotdir"
      - "./data/anythingllm/collector/outputs/:/app/collector/outputs"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - STORAGE_DIR=${STORAGE_DIR}
      - JWT_SECRET=${JWT_SECRET}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_LLM_MODEL_PREF=${GEMINI_LLM_MODEL_PREF}
      - EMBEDDING_ENGINE=${EMBEDDING_ENGINE}
      - GEMINI_EMBEDDING_API_KEY=${GEMINI_EMBEDDING_API_KEY}
      - EMBEDDING_MODEL_PREF=${EMBEDDING_MODEL_PREF}
      - VECTOR_DB=${VECTOR_DB}
      - DATABASE_URL=${DATABASE_URL}
      - PGVECTOR_CONNECTION_STRING=${PGVECTOR_CONNECTION_STRING}
      - PGVECTOR_TABLE_NAME=${PGVECTOR_TABLE_NAME}
      - AGENT_GSE_KEY=${AGENT_GSE_KEY}
      - AGENT_GSE_CTX=${AGENT_GSE_CTX}
    depends_on:
      warehouse_db:
        condition: service_healthy
    networks:
      - ndsnet
  trino:
    image: "trinodb/trino:latest"
    hostname: trino
    ports:
      - "8080:8080"
    volumes:
      - ./application/trino/etc:/usr/lib/trino/etc:ro
      - ./application/trino/catalog:/etc/trino/catalog
    depends_on:
      warehouse_db:
        condition: service_healthy
      minio:
        condition: service_healthy
      hive-metastore:
        condition: service_started
    networks:
      - ndsnet

  # cloudbeaver:
  #   image: dbeaver/cloudbeaver:latest
  #   volumes:
  #     # optional to persist data locally
  #     - ./application/cloudbeaver/workspace:/opt/cloudbeaver/workspace
  #     - ./application/cloudbeaver/conf:/opt/cloudbeaver/conf
  #   ports:
  #     - 8978:8978
  #     - 9030:9030
  #     - 8030:8030
  #     - 8040:8040
  #   networks:
  #     - ndsnet
      
  # cubejs:
  #   image: cubejs/cube:latest
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - ./application/cube/cubejs/conf:/cube/conf
  #   environment:
  #     - CUBEJS_CUBESTORE_HOST=cubestore_router
  #     - CUBEJS_DEV_MODE=true
  #   networks:
  #     - ndsnet

  # cubestore_router:
  #   restart: always
  #   image: cubejs/cubestore:latest
  #   environment:
  #     - CUBESTORE_WORKERS=cubestore_worker:10001
  #     - CUBESTORE_REMOTE_DIR=/cube/data
  #     - CUBESTORE_META_PORT=9999
  #     - CUBESTORE_SERVER_NAME=cubestore_router:9999
  #   volumes:
  #     - ./application/cube/cubestore:/cube/data
  #   networks:
  #     - ndsnet
 
  # cubestore_worker:
  #   restart: always
  #   image: cubejs/cubestore:latest
  #   environment:
  #     - CUBESTORE_WORKERS=cubestore_worker:10001
  #     - CUBESTORE_SERVER_NAME=cubestore_worker:10001
  #     - CUBESTORE_WORKER_PORT=10001
  #     - CUBESTORE_REMOTE_DIR=/cube/data
  #     - CUBESTORE_META_ADDR=cubestore_router:9999
  #   volumes:
  #     - ./application/cube/cubestore:/cube/data
  #   depends_on:
  #     - cubestore_router
  #   networks:
  #     - ndsnet
 
  # clickhouse-server:
  #   image: clickhouse/clickhouse-server:latest
  #   ports:
  #     - 8123:8123
  #     - 9010:9000
  #   volumes:
  #     - ./application/clickhouse/etc:/etc/clickhouse-server/
  #   networks:
  #     - ndsnet

networks:
  ndsnet:
    driver: bridge