project_type: standalone

variables_dir: ~/.mage_data
# remote_variables_dir: s3://bucket/path_prefix

variables_retention_period: '90d'

emr_config:
# spark_config:
#   # Application name
#   app_name: Mage_Spark
#   spark_master: local
#   executor_env: {}
#   spark_jars: []
#   spark_home:
#   others: {}
#   use_custom_session: false
#   custom_session_var_name: spark
notification_config:
  alert_on:
  - trigger_failure
  - trigger_passed_sla
  slack_config:
    webhook_url: "{{ env_var('MAGE_SLACK_WEBHOOK_URL') }}"
  teams_config:
    webhook_url: "{{ env_var('MAGE_TEAMS_WEBHOOK_URL') }}"
project_uuid: ede6eb5d3ad44538b0d1a5b922f99ed9
help_improve_mage: true
features:
  add_new_block_v2: true
  compute_management: true
  data_integration_in_batch_pipeline: true
  interactions: true
  display_local_timezone: true
  notebook_block_output_split_view: true
  operation_history: true
  code_block_v2: true
  custom_design: true
  dbt_v2: true
  global_hooks: true
  project_platform: true
  command_center: true
pipelines:
remote_variables_dir:
