description: null
name: null
pipeline:
  blocks:
  - all_upstream_blocks_executed: true
    color: null
    configuration:
      file_path: null
    downstream_blocks:
    - no_transform_blocks
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: vietnam_stock_finance_data/vndirect_Balance_Sheet_Data
    retry_config: null
    status: executed
    timeout: null
    type: data_loader
    upstream_blocks: []
    uuid: vietnam_stock_finance_data/vndirect_balance_sheet_data
  - all_upstream_blocks_executed: true
    color: null
    configuration:
      file_path: null
    downstream_blocks:
    - finance_stock_demo/save_to_minio
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: no_transform_blocks
    retry_config: null
    status: executed
    timeout: null
    type: transformer
    upstream_blocks:
    - vietnam_stock_finance_data/vndirect_balance_sheet_data
    uuid: no_transform_blocks
  - all_upstream_blocks_executed: true
    color: null
    configuration:
      dynamic: true
      file_path: null
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: finance_stock_demo/save_to_minio
    retry_config: null
    status: updated
    timeout: null
    type: data_exporter
    upstream_blocks:
    - no_transform_blocks
    uuid: finance_stock_demo/save_to_minio
  callbacks: []
  concurrency_config: {}
  conditionals: []
  created_at: '2023-11-11 08:30:47.168576+00:00'
  data_integration: null
  description: null
  executor_config: {}
  executor_count: 1
  executor_type: null
  extensions: {}
  name: balance_sheet_pipeline
  notification_config: {}
  retry_config: {}
  run_pipeline_in_one_process: false
  spark_config: {}
  tags:
  - finance_demo
  type: python
  updated_at: '2023-12-02 16:24:25'
  uuid: balance_sheet_pipeline
  variables:
    bucket: dwhfilesystem
    folder_path: raw_area/vn_finance_project/vn_stock_balance_sheet
  widgets: []
tags: []
user: {}
