name: 'data_warehouse'
version: '1.0.0'
config-version: 2

profile: 'data_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ setup_minio_secret() }}"

models:
  data_warehouse:
    raw:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +on_schema_change: sync_all_columns
      +schema: raw

    stg:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +on_schema_change: sync_all_columns
      +schema: stg

    bdh:
      +materialized: table
      +schema: bdh

    adl:
      +materialized: table
      +schema: adl
