data_warehouse:
  outputs:
    prod:
      dbname: 'warehouse'
      host: 'warehouse_db'
      password: warehouse
      port: 5432
      schema: public
      type: postgres
      user: warehouse
  target: prod
