triggers:
- envs: []
  last_enabled_at: 2024-02-20 15:57:02.289840+00:00
  name: restless music
  pipeline_uuid: finance_master_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2023-12-01 16:45:00
  status: active
  variables: null
