connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://warehouse_db:5432/warehouse
iceberg.jdbc-catalog.connection-user=warehouse
iceberg.jdbc-catalog.connection-password=warehouse
iceberg.jdbc-catalog.catalog-name=iceberg
iceberg.jdbc-catalog.default-warehouse-dir=s3://dwhfilesystem/
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=admin
s3.aws-secret-key=admin123
